name: Auto Update Data Pasaran Pools

on:
  schedule:
    # Menggunakan zona waktu UTC (WIB dikurang 7 jam)
    # Cron ini berjalan setiap jam pada menit ke :01, :15, :30 (Menangkap update jam 13:00, 16:00, 19:00, 21:00, 22:00, 23:00, 00:01 WIB)
    - cron: '1,15,30 * * * *'
  workflow_dispatch: 

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Ambil Kode Repositori
      uses: actions/checkout@v3

    - name: Pasang Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Pasang Library Pendukung
      run: pip install requests

    - name: Jalankan Scraper Taiwan
      run: python scraper.py

    - name: Jalankan Scraper Macau
      run: python scraper_macau.py

    - name: Simpan Semua Data Terbaru
      run: |
        git config --global user.name "Sistem Otomatisasi"
        git config --global user.email "actions@github.com"
        git add result.json result_macau.json
        git commit -m "Update hasil pasaran otomatis: $(date)" || exit 0
        git push
