name: Auto Update Data Togel

on:
  schedule:
    - cron: '15 5 * * *'
    - cron: '15 7 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Install Dependencies
      run: npm install

    - name: Run Scraper Bots
      run: |
        node bot/cambodia.js || true
        node bot/sydney.js || true

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@://github.com"
        git add result/*.html
        git diff-index --quiet HEAD || git commit -m "Auto Update Data Pasaran Node24"
        git push
