name: Robot Otomatis Cambodia

on:
  schedule:
    - cron: '15 5 * * *' # Jam 12:15 WIB siang
  workflow_dispatch: # Tombol darurat manual dari HP

jobs:
  jalankan-robot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Ambil Kode Repositori
      uses: actions/checkout@v4

    - name: Siapkan Sistem Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Jalankan Skrip Memulung Data
      run: node result/grabber.js

    - name: Simpan Otomatis Ke Repositori GitHub
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@://github.com"
        git add result/cambodia.js
        git diff-index --quiet HEAD || (git commit -m "Robot: Sinkronisasi paito terbaru" && git push)
